
# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV.fetch("BASE_SOURCE_DATABASE_HOST") { "localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  port: <%= ENV.fetch("BASE_SOURCE_DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("BASE_SOURCE_DATABASE_NAME") { "base_source_development" } %>
  password: <%= ENV.fetch("BASE_SOURCE_DEVELOPMENT_PASSWORD") { "postgres" } %>

test:
  <<: *default
  database: <%= ENV.fetch("BASE_SOURCE_DATABASE_NAME") { "base_source_test" } %>
  password: <%= ENV.fetch("BASE_SOURCE_PASSWORD") { "postgres" } %>

production:
  <<: *default
  database: <%= ENV.fetch("BASE_SOURCE_DATABASE_NAME") { "base_source_production" } %>
  username: <%= ENV.fetch("BASE_SOURCE_USERNAME") { "base_source" } %>
  password: <%= ENV["BASE_SOURCE_PASSWORD"] %>

staging:
  <<: *default
  database: <%= ENV.fetch("BASE_SOURCE_DATABASE_NAME") { "base_source_staging" } %>
  username: <%= ENV.fetch("BASE_SOURCE_USERNAME") { "base_source" } %>
  password: <%= ENV["BASE_SOURCE_PASSWORD"] %>
